-- Composite tenant keys let PostgreSQL reject new cross-organization references.
-- Foreign keys are NOT VALID: legacy rows remain untouched until a controlled audit.
ALTER TABLE stores ADD CONSTRAINT stores_org_id_unique UNIQUE (organization_id,id);
ALTER TABLE users ADD CONSTRAINT users_org_id_unique UNIQUE (organization_id,id);
ALTER TABLE products ADD CONSTRAINT products_org_id_unique UNIQUE (organization_id,id);
ALTER TABLE shifts ADD CONSTRAINT shifts_org_id_unique UNIQUE (organization_id,id);
ALTER TABLE sales ADD CONSTRAINT sales_org_id_unique UNIQUE (organization_id,id);
ALTER TABLE customers ADD CONSTRAINT customers_org_id_unique UNIQUE (organization_id,id);
ALTER TABLE suppliers ADD CONSTRAINT suppliers_org_id_unique UNIQUE (organization_id,id);
ALTER TABLE supplier_invoices ADD CONSTRAINT supplier_invoices_org_id_unique UNIQUE (organization_id,id);
ALTER TABLE customer_ledger ADD CONSTRAINT customer_ledger_org_id_unique UNIQUE (organization_id,id);
ALTER TABLE billing_drafts ADD CONSTRAINT billing_drafts_org_id_unique UNIQUE (organization_id,id);
ALTER TABLE billing_receipts ADD CONSTRAINT billing_receipts_org_id_unique UNIQUE (organization_id,id);

ALTER TABLE users ADD CONSTRAINT users_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE inventory_balances ADD CONSTRAINT inventory_balances_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE inventory_balances ADD CONSTRAINT inventory_balances_product_tenant_fk FOREIGN KEY (organization_id,product_id) REFERENCES products(organization_id,id) NOT VALID;
ALTER TABLE inventory_batches ADD CONSTRAINT inventory_batches_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE inventory_batches ADD CONSTRAINT inventory_batches_product_tenant_fk FOREIGN KEY (organization_id,product_id) REFERENCES products(organization_id,id) NOT VALID;
ALTER TABLE product_serials ADD CONSTRAINT product_serials_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE product_serials ADD CONSTRAINT product_serials_product_tenant_fk FOREIGN KEY (organization_id,product_id) REFERENCES products(organization_id,id) NOT VALID;
ALTER TABLE product_serials ADD CONSTRAINT product_serials_sale_tenant_fk FOREIGN KEY (organization_id,sale_id) REFERENCES sales(organization_id,id) NOT VALID;
ALTER TABLE stock_movements ADD CONSTRAINT stock_movements_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE stock_movements ADD CONSTRAINT stock_movements_product_tenant_fk FOREIGN KEY (organization_id,product_id) REFERENCES products(organization_id,id) NOT VALID;
ALTER TABLE stock_movements ADD CONSTRAINT stock_movements_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE shifts ADD CONSTRAINT shifts_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE shifts ADD CONSTRAINT shifts_cashier_tenant_fk FOREIGN KEY (organization_id,cashier_id) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE shift_movements ADD CONSTRAINT shift_movements_shift_tenant_fk FOREIGN KEY (organization_id,shift_id) REFERENCES shifts(organization_id,id) NOT VALID;
ALTER TABLE shift_movements ADD CONSTRAINT shift_movements_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE sales ADD CONSTRAINT sales_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE sales ADD CONSTRAINT sales_shift_tenant_fk FOREIGN KEY (organization_id,shift_id) REFERENCES shifts(organization_id,id) NOT VALID;
ALTER TABLE sales ADD CONSTRAINT sales_seller_tenant_fk FOREIGN KEY (organization_id,seller_id) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE sales ADD CONSTRAINT sales_customer_tenant_fk FOREIGN KEY (organization_id,customer_id) REFERENCES customers(organization_id,id) NOT VALID;
ALTER TABLE sale_returns ADD CONSTRAINT sale_returns_sale_tenant_fk FOREIGN KEY (organization_id,sale_id) REFERENCES sales(organization_id,id) NOT VALID;
ALTER TABLE sale_returns ADD CONSTRAINT sale_returns_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE sale_returns ADD CONSTRAINT sale_returns_product_tenant_fk FOREIGN KEY (organization_id,product_id) REFERENCES products(organization_id,id) NOT VALID;
ALTER TABLE sale_returns ADD CONSTRAINT sale_returns_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE supplier_invoices ADD CONSTRAINT supplier_invoices_supplier_tenant_fk FOREIGN KEY (organization_id,supplier_id) REFERENCES suppliers(organization_id,id) NOT VALID;
ALTER TABLE supplier_invoices ADD CONSTRAINT supplier_invoices_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE supplier_payments ADD CONSTRAINT supplier_payments_supplier_tenant_fk FOREIGN KEY (organization_id,supplier_id) REFERENCES suppliers(organization_id,id) NOT VALID;
ALTER TABLE supplier_payments ADD CONSTRAINT supplier_payments_invoice_tenant_fk FOREIGN KEY (organization_id,invoice_id) REFERENCES supplier_invoices(organization_id,id) NOT VALID;
ALTER TABLE supplier_payments ADD CONSTRAINT supplier_payments_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE supplier_payments ADD CONSTRAINT supplier_payments_shift_tenant_fk FOREIGN KEY (organization_id,shift_id) REFERENCES shifts(organization_id,id) NOT VALID;
ALTER TABLE supplier_payments ADD CONSTRAINT supplier_payments_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE expenses ADD CONSTRAINT expenses_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE expenses ADD CONSTRAINT expenses_shift_tenant_fk FOREIGN KEY (organization_id,shift_id) REFERENCES shifts(organization_id,id) NOT VALID;
ALTER TABLE expenses ADD CONSTRAINT expenses_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE stock_transfers ADD CONSTRAINT stock_transfers_from_store_tenant_fk FOREIGN KEY (organization_id,from_store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE stock_transfers ADD CONSTRAINT stock_transfers_to_store_tenant_fk FOREIGN KEY (organization_id,to_store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE stock_transfers ADD CONSTRAINT stock_transfers_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE inventory_counts ADD CONSTRAINT inventory_counts_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE inventory_counts ADD CONSTRAINT inventory_counts_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE inventory_counts ADD CONSTRAINT inventory_counts_reviewed_by_tenant_fk FOREIGN KEY (organization_id,reviewed_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE sale_holds ADD CONSTRAINT sale_holds_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE sale_holds ADD CONSTRAINT sale_holds_user_tenant_fk FOREIGN KEY (organization_id,user_id) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE sale_holds ADD CONSTRAINT sale_holds_shift_tenant_fk FOREIGN KEY (organization_id,shift_id) REFERENCES shifts(organization_id,id) NOT VALID;
ALTER TABLE business_days ADD CONSTRAINT business_days_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE business_days ADD CONSTRAINT business_days_closed_by_tenant_fk FOREIGN KEY (organization_id,closed_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE billing_drafts ADD CONSTRAINT billing_drafts_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE billing_receipts ADD CONSTRAINT billing_receipts_uploaded_by_tenant_fk FOREIGN KEY (organization_id,uploaded_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE billing_payments ADD CONSTRAINT billing_payments_draft_tenant_fk FOREIGN KEY (organization_id,draft_id) REFERENCES billing_drafts(organization_id,id) NOT VALID;
ALTER TABLE billing_payments ADD CONSTRAINT billing_payments_receipt_tenant_fk FOREIGN KEY (organization_id,receipt_id) REFERENCES billing_receipts(organization_id,id) NOT VALID;
ALTER TABLE billing_payments ADD CONSTRAINT billing_payments_submitted_by_tenant_fk FOREIGN KEY (organization_id,submitted_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE telegram_link_tokens ADD CONSTRAINT telegram_link_tokens_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE telegram_link_tokens ADD CONSTRAINT telegram_link_tokens_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE telegram_connections ADD CONSTRAINT telegram_connections_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE telegram_connections ADD CONSTRAINT telegram_connections_linked_by_tenant_fk FOREIGN KEY (organization_id,linked_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE notification_outbox ADD CONSTRAINT notification_outbox_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE file_assets ADD CONSTRAINT file_assets_uploaded_by_tenant_fk FOREIGN KEY (organization_id,uploaded_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE customers ADD CONSTRAINT customers_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE customer_ledger ADD CONSTRAINT customer_ledger_customer_tenant_fk FOREIGN KEY (organization_id,customer_id) REFERENCES customers(organization_id,id) NOT VALID;
ALTER TABLE customer_ledger ADD CONSTRAINT customer_ledger_store_tenant_fk FOREIGN KEY (organization_id,store_id) REFERENCES stores(organization_id,id) NOT VALID;
ALTER TABLE customer_ledger ADD CONSTRAINT customer_ledger_sale_tenant_fk FOREIGN KEY (organization_id,sale_id) REFERENCES sales(organization_id,id) NOT VALID;
ALTER TABLE customer_ledger ADD CONSTRAINT customer_ledger_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
ALTER TABLE customer_payment_allocations ADD CONSTRAINT customer_allocations_customer_tenant_fk FOREIGN KEY (organization_id,customer_id) REFERENCES customers(organization_id,id) NOT VALID;
ALTER TABLE customer_payment_allocations ADD CONSTRAINT customer_allocations_payment_tenant_fk FOREIGN KEY (organization_id,payment_ledger_id) REFERENCES customer_ledger(organization_id,id) NOT VALID;
ALTER TABLE customer_payment_allocations ADD CONSTRAINT customer_allocations_credit_tenant_fk FOREIGN KEY (organization_id,credit_ledger_id) REFERENCES customer_ledger(organization_id,id) NOT VALID;
ALTER TABLE customer_loyalty_ledger ADD CONSTRAINT customer_loyalty_customer_tenant_fk FOREIGN KEY (organization_id,customer_id) REFERENCES customers(organization_id,id) NOT VALID;
ALTER TABLE customer_loyalty_ledger ADD CONSTRAINT customer_loyalty_sale_tenant_fk FOREIGN KEY (organization_id,sale_id) REFERENCES sales(organization_id,id) NOT VALID;
ALTER TABLE customer_loyalty_ledger ADD CONSTRAINT customer_loyalty_created_by_tenant_fk FOREIGN KEY (organization_id,created_by) REFERENCES users(organization_id,id) NOT VALID;
